printf("Entre com os dados: ");
printf("\nPosicao: %d", pos);
printf("\nCodigo: ");
scanf("%d", &cdx.codigo);
printf("\nArtista: ");
fflush(stdin);fgets(cdx.artista, 20,stdin);
printf("\nNome: ");
fflush(stdin);fgets(cdx.nome, 50,stdin);
printf("\nAno: ");
scanf("%d", &cdx.ano);
printf("\nFaixas: ");
scanf("%d", &cdx.faixas);
printf("\nValor: ");
scanf("%f", &cdx.valor);
fseek(arq_cd, (long)sizeof(struct registro_cd)*pos, SEEK_SET );
fwrite(&cdx, sizeof(registro_cdx), 1, arq_cd);
cdx.codigo = pos+1;
cdx.ano = pos_rel;
fseek(arq_cd, (long)sizeof(struct registro_cd)*0, SEEK_SET );
fwrite(&cdx, sizeof(registro_cdx), 1, arq_cd);	
